/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.13 and DSP System Toolbox 9.15.
 * Generated on: 23-Mar-2023 17:29:23
 */

/*
 * Discrete-Time FIR Filter (real)
 * -------------------------------
 * Filter Structure  : Direct-Form FIR
 * Filter Length     : 18
 * Stable            : Yes
 * Linear Phase      : Yes (Type 2)
 * Arithmetic        : fixed
 * Numerator         : s14,15 -> [-2.500000e-01 2.500000e-01)
 * Input             : s10,10 -> [-5.000000e-01 5.000000e-01)
 * Filter Internals  : Full Precision
 *   Output          : s26,25 -> [-1 1)  (auto determined)
 *   Product         : s23,25 -> [-1.250000e-01 1.250000e-01)  (auto determined)
 *   Accumulator     : s26,25 -> [-1 1)  (auto determined)
 *   Round Mode      : No rounding
 *   Overflow Mode   : No overflow
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
#include <stdint.h>

/*
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2022b\extern\include\tmwtypes.h 
 */
#define BL = 18;
const int16_t B[18] = {
     -932,  -2674,  -3508,  -2706,      0,   4254,   9124,  13372,  15842,
    15842,  13372,   9124,   4254,      0,  -2706,  -3508,  -2674,   -932
};
